// AI CAMPUS EVENT ASSISTANT — SEED DEMONSTRATION DATASET
// All demonstration items are explicitly tagged with is_demonstration: true

export const INITIAL_PROFILES = [
  {
    id: 'user-student-sanjay',
    email: 'sanjaypravinr.cs25@bitsathy.ac.in',
    display_name: 'SANJAYPRAVIN R',
    role: 'student',
    department: 'Computer Science and Engineering',
    academic_year: '4th Year (2021-2025)',
    student_id: '7376211CS142',
    avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    interests: ['Systems Programming', 'Hackathons', 'C Programming'],
    is_demonstration: true,
  },

  {
    id: 'user-student-001',
    email: 'alex.student@campus.edu',
    display_name: 'Alex Rivera (Demo Student)',
    role: 'student',
    department: 'Computer Science & Engineering',
    academic_year: '3rd Year',
    student_id: 'CS-2023-4091',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    interests: ['AI/ML', 'Hackathons', 'Cloud Architecture'],
    is_demonstration: true,
  },
  {
    id: 'user-admin-001',
    email: 'sarah.admin@campus.edu',
    display_name: 'Dr. Sarah Jenkins (Demo Admin)',
    role: 'admin',
    department: 'Student Affairs & Innovation',
    academic_year: 'Faculty Lead',
    student_id: 'FAC-2018-012',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    interests: ['Event Operations', 'Innovation Council'],
    is_demonstration: true,
  },
  {
    id: 'user-student-002',
    email: 'liam.chen@campus.edu',
    display_name: 'Liam Chen (Demo Student)',
    role: 'student',
    department: 'Electrical Engineering',
    academic_year: '4th Year',
    student_id: 'EE-2022-1088',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    interests: ['Robotics', 'Hardware', 'Sports'],
    is_demonstration: true,
  },
  {
    id: 'user-student-003',
    email: 'priya.sharma@campus.edu',
    display_name: 'Priya Sharma (Demo Student)',
    role: 'student',
    department: 'Information Technology',
    academic_year: '2nd Year',
    student_id: 'IT-2024-5521',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    interests: ['UI/UX Design', 'Coding Competitions'],
    is_demonstration: true,
  }
];

export const INITIAL_EVENTS = [
  {
    id: 'evt-001',
    title: 'HACKSPACE 2026: Campus AI & Systems Hackathon',
    slug: 'hackspace-2026-hackathon',
    description: 'The flagship 36-hour inter-collegiate hackathon challenging student engineers to build high-impact autonomous systems, decentralized networks, and smart campus solutions. Mentors from top tech firms will be present around the clock.',
    category: 'Hackathon',
    poster_url: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80',
    organizer_name: 'Vision Builders Council',
    venue: 'Main Tech Complex, Grand Arena',
    venue_otp: '849201',
    event_format: 'in-person',
    start_at: new Date(Date.now() + 5 * 86400000).toISOString(),
    end_at: new Date(Date.now() + 7 * 86400000).toISOString(),
    registration_deadline: new Date(Date.now() + 4 * 86400000).toISOString(),
    capacity: 150,
    registered_count: 42,
    minimum_team_size: 2,
    maximum_team_size: 4,
    eligibility_type: 'pcdp_skill',
    required_skill: 'C Programming',
    required_skill_level: 2,
    eligibility_rules: 'Requires completed C Programming Level 2 on the BIT Sathy PCDP Portal (ps.bitsathy.ac.in).',
    event_rules: 'Teams must consist of 2 to 4 members. Pre-built code is strictly disallowed. Hardware tracks provided on-site.',
    status: 'published',
    created_by: 'user-admin-001',
    is_featured: true,
    is_demonstration: true,
  },
  {
    id: 'evt-002',
    title: 'Advanced Cloud Architecture & Kubernetes Masterclass',
    slug: 'advanced-cloud-kubernetes-masterclass',
    description: 'An intensive hands-on technical workshop covering modern microservices orchestration, service meshes, zero-trust container security, and GitOps delivery pipelines.',
    category: 'Technical Workshop',
    poster_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    organizer_name: 'Campus Cloud Computing Club',
    venue: 'Computer Lab 402, Turing Science Block',
    venue_otp: '492817',
    event_format: 'hybrid',
    start_at: new Date(Date.now() + 2 * 86400000).toISOString(),
    end_at: new Date(Date.now() + 2 * 86400000 + 4 * 3600000).toISOString(),
    registration_deadline: new Date(Date.now() + 1 * 86400000).toISOString(),
    capacity: 60,
    registered_count: 51,
    minimum_team_size: 1,
    maximum_team_size: 1,
    eligibility_type: 'fcfs',
    required_skill: null,
    required_skill_level: null,
    eligibility_rules: 'First-Come-First-Served (FCFS) open entry until capacity limit.',
    event_rules: 'Bring your own laptop with 8GB+ RAM. Cloud sandbox credits will be provisioned on entry.',
    status: 'published',
    created_by: 'user-admin-001',
    is_featured: true,
    is_demonstration: true,
  },
  {
    id: 'evt-003',
    title: 'CodeCraft 2026: Speed Algorithm Championship',
    slug: 'codecraft-2026-speed-algo',
    description: 'A high-octane 3-hour competitive programming sprint testing data structures, graph theory, dynamic programming, and numerical algorithms under strict time execution constraints.',
    category: 'Coding Competition',
    poster_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    organizer_name: 'ACM Student Chapter',
    venue: 'Virtual Online Judge Portal',
    venue_otp: '621940',
    event_format: 'virtual',
    start_at: new Date(Date.now() + 8 * 86400000).toISOString(),
    end_at: new Date(Date.now() + 8 * 86400000 + 3 * 3600000).toISOString(),
    registration_deadline: new Date(Date.now() + 6 * 86400000).toISOString(),
    capacity: 200,
    registered_count: 115,
    minimum_team_size: 1,
    maximum_team_size: 1,
    eligibility_rules: 'Open to all enrolled students across all departments.',
    event_rules: 'Individual participation only. Webcams required for virtual proctoring. Code plagiarism checks strictly enforced.',
    status: 'published',
    created_by: 'user-admin-001',
    is_featured: true,
    is_demonstration: true,
  },
  {
    id: 'evt-004',
    title: 'NextGen AI & Ethics: Dean\'s Leadership Seminar',
    slug: 'nextgen-ai-ethics-deans-seminar',
    description: 'Keynote addresses and panel debates featuring industry research scientists discussing ethical boundaries, agentic safety, bias mitigation, and regulatory frontiers in computing.',
    category: 'Seminar',
    poster_url: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=80',
    organizer_name: 'Dean of Academic Affairs',
    venue: 'Saraswati Convention Center',
    venue_otp: '730192',
    event_format: 'in-person',
    start_at: new Date(Date.now() + 12 * 86400000).toISOString(),
    end_at: new Date(Date.now() + 12 * 86400000 + 5 * 3600000).toISOString(),
    registration_deadline: new Date(Date.now() + 10 * 86400000).toISOString(),
    capacity: 300,
    registered_count: 180,
    minimum_team_size: 1,
    maximum_team_size: 1,
    eligibility_rules: 'Open to all campus departments and faculty members.',
    event_rules: 'Smart-casual attire recommended. Interactive Q&A session follows panel discussion.',
    status: 'published',
    created_by: 'user-admin-001',
    is_featured: false,
    is_demonstration: true,
  },
  {
    id: 'evt-005',
    title: 'Vibrance 2026: Annual Inter-College Cultural Gala',
    slug: 'vibrance-2026-cultural-gala',
    description: 'A magnificent 2-day festival celebrating music, theatrical arts, contemporary dance, acoustic performances, and university cultural diversity.',
    category: 'Cultural Event',
    poster_url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80',
    organizer_name: 'Student Cultural Federation',
    venue: 'Open Air Amphitheatre',
    venue_otp: '915382',
    event_format: 'in-person',
    start_at: new Date(Date.now() + 20 * 86400000).toISOString(),
    end_at: new Date(Date.now() + 22 * 86400000).toISOString(),
    registration_deadline: new Date(Date.now() + 15 * 86400000).toISOString(),
    capacity: 800,
    registered_count: 520,
    minimum_team_size: 1,
    maximum_team_size: 8,
    eligibility_rules: 'All college students with valid student credentials.',
    event_rules: 'Valid digital or physical pass required at gates. Security guidelines apply.',
    status: 'published',
    created_by: 'user-admin-001',
    is_featured: false,
    is_demonstration: true,
  },
  {
    id: 'evt-006',
    title: 'Titan Cup: Inter-Departmental 5v5 Futsal Tournament',
    slug: 'titan-cup-futsal-tournament',
    description: 'Fast-paced indoor soccer tournament spanning 3 rounds of knockouts. Compete for the prestigious rolling trophy and department bragging rights.',
    category: 'Sports Event',
    poster_url: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=1200&q=80',
    organizer_name: 'Department of Physical Education',
    venue: 'Indoor Sports Arena Court 1 & 2',
    venue_otp: '381946',
    event_format: 'in-person',
    start_at: new Date(Date.now() + 14 * 86400000).toISOString(),
    end_at: new Date(Date.now() + 16 * 86400000).toISOString(),
    registration_deadline: new Date(Date.now() + 10 * 86400000).toISOString(),
    capacity: 32,
    registered_count: 28,
    minimum_team_size: 5,
    maximum_team_size: 7,
    eligibility_rules: 'Current students with sports clearance waiver on file.',
    event_rules: 'Standard FIFA futsal rules. Team jerseys and shin guards compulsory.',
    status: 'published',
    created_by: 'user-admin-001',
    is_featured: false,
    is_demonstration: true,
  },
  {
    id: 'evt-007',
    title: 'Campus CleanTech & Sustainability Innovation Challenge',
    slug: 'cleantech-sustainability-challenge-2026',
    description: 'Pitch prototype hardware and software solutions to reduce campus energy waste, optimize water recycling, and cut carbon footprints with $5,000 seed funding.',
    category: 'Innovation Challenge',
    poster_url: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=1200&q=80',
    organizer_name: 'Sustainability & Green Campus Initiative',
    venue: 'Innovation Hub Pitch Stage',
    venue_otp: '554192',
    event_format: 'hybrid',
    start_at: new Date(Date.now() + 25 * 86400000).toISOString(),
    end_at: new Date(Date.now() + 26 * 86400000).toISOString(),
    registration_deadline: new Date(Date.now() + 18 * 86400000).toISOString(),
    capacity: 50,
    registered_count: 18,
    minimum_team_size: 2,
    maximum_team_size: 5,
    eligibility_rules: 'Multidisciplinary student teams across any degree program.',
    event_rules: 'Executive summary and functioning prototype demonstration required at semifinal pitch.',
    status: 'published',
    created_by: 'user-admin-001',
    is_featured: false,
    is_demonstration: true,
  }
];

export const INITIAL_REGISTRATIONS = [
  {
    id: 'reg-001',
    public_registration_id: 'ACE-2026-X89K2L',
    event_id: 'evt-001',
    user_id: 'user-student-001',
    team_id: 'team-001',
    registration_type: 'team',
    status: 'confirmed',
    qr_payload: 'ACE-VERIFY:ACE-2026-X89K2L:evt-001:user-student-001',
    registered_at: new Date(Date.now() - 24 * 3600000).toISOString(),
    cancelled_at: null,
    is_demonstration: true,
  },
  {
    id: 'reg-002',
    public_registration_id: 'ACE-2026-C44T9Q',
    event_id: 'evt-002',
    user_id: 'user-student-001',
    team_id: null,
    registration_type: 'individual',
    status: 'confirmed',
    qr_payload: 'ACE-VERIFY:ACE-2026-C44T9Q:evt-002:user-student-001',
    registered_at: new Date(Date.now() - 48 * 3600000).toISOString(),
    cancelled_at: null,
    is_demonstration: true,
  },
  {
    id: 'reg-003',
    public_registration_id: 'ACE-2026-M71P3Z',
    event_id: 'evt-003',
    user_id: 'user-student-002',
    team_id: null,
    registration_type: 'individual',
    status: 'attended',
    qr_payload: 'ACE-VERIFY:ACE-2026-M71P3Z:evt-003:user-student-002',
    registered_at: new Date(Date.now() - 72 * 3600000).toISOString(),
    cancelled_at: null,
    is_demonstration: true,
  }
];

export const INITIAL_TEAMS = [
  {
    id: 'team-001',
    name: 'Neural Knights',
    team_code: 'NK-7782',
    event_id: 'evt-001',
    leader_id: 'user-student-001',
    created_at: new Date(Date.now() - 26 * 3600000).toISOString(),
    is_demonstration: true,
  }
];

export const INITIAL_TEAM_MEMBERS = [
  {
    id: 'tm-001',
    team_id: 'team-001',
    user_id: 'user-student-001',
    membership_status: 'accepted',
    role: 'leader',
    created_at: new Date(Date.now() - 26 * 3600000).toISOString(),
  },
  {
    id: 'tm-002',
    team_id: 'team-001',
    user_id: 'user-student-003',
    membership_status: 'accepted',
    role: 'member',
    created_at: new Date(Date.now() - 22 * 3600000).toISOString(),
  }
];

export const INITIAL_ATTENDANCE = [
  {
    id: 'att-001',
    registration_id: 'reg-003',
    event_id: 'evt-003',
    venue_name: 'Virtual Online Judge Portal',
    checked_in_at: new Date(Date.now() - 12 * 3600000).toISOString(),
    checked_in_by: 'user-admin-001',
    verification_method: 'venue_otp',
    is_demonstration: true,
  }
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif-001',
    user_id: 'user-student-001',
    title: 'Registration Confirmed!',
    message: 'You have successfully registered for HACKSPACE 2026 with team Neural Knights. When at the venue, use the Venue OTP to mark your squad Present.',
    notification_type: 'registration',
    related_event_id: 'evt-001',
    is_read: false,
    created_at: new Date(Date.now() - 24 * 3600000).toISOString(),
    is_demonstration: true,
  }
];